services:
  nginx:
    image: ${NGINX_IMAGE}
    hostname: ${NGINX_HOSTNAME}
    container_name: ${NGINX_CONTAINER_NAME}
    depends_on:
      backend_app:
        condition: service_started
        restart: true
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf:ro
      - ${NGINX_PROXY_CONF_PATH}:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend_network
    ports:
      - ${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}

  backend_app:
    image: ${BACKEND_IMAGE}
    hostname: ${BACKEND_HOSTNAME}
    container_name: ${BACKEND_CONTAINER_NAME}
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
